function [du, info] = MPC_QP(y, r, A, B, N1, N2, Nu, alpha, lam, reset, ...
                    C, D, wy, umin, umax, dumin, dumax, u_init, du_init, ...
                    L, use_quadprog, mode, u_applied, solve_when_inactive)
%MPC_QP Constrained MPC wrapper with optional supervisor inputs.
%   This wrapper preserves the public MATLAB entry point and delegates the
%   implementation to MPC_QP_core so Simulink and script callers can share
%   the same controller logic.

    if nargout > 1
        if nargin == 21
            [du, info] = MPC_QP_core(y, r, A, B, N1, N2, Nu, alpha, lam, reset, ...
                                     C, D, wy, umin, umax, dumin, dumax, u_init, du_init, ...
                                     L, use_quadprog);
        elseif nargin == 22
            [du, info] = MPC_QP_core(y, r, A, B, N1, N2, Nu, alpha, lam, reset, ...
                                     C, D, wy, umin, umax, dumin, dumax, u_init, du_init, ...
                                     L, use_quadprog, mode);
        elseif nargin == 23
            [du, info] = MPC_QP_core(y, r, A, B, N1, N2, Nu, alpha, lam, reset, ...
                                     C, D, wy, umin, umax, dumin, dumax, u_init, du_init, ...
                                     L, use_quadprog, mode, u_applied);
        else
            [du, info] = MPC_QP_core(y, r, A, B, N1, N2, Nu, alpha, lam, reset, ...
                                     C, D, wy, umin, umax, dumin, dumax, u_init, du_init, ...
                                     L, use_quadprog, mode, u_applied, solve_when_inactive);
        end
    else
        if nargin == 21
            du = MPC_QP_core(y, r, A, B, N1, N2, Nu, alpha, lam, reset, ...
                             C, D, wy, umin, umax, dumin, dumax, u_init, du_init, ...
                             L, use_quadprog);
        elseif nargin == 22
            du = MPC_QP_core(y, r, A, B, N1, N2, Nu, alpha, lam, reset, ...
                             C, D, wy, umin, umax, dumin, dumax, u_init, du_init, ...
                             L, use_quadprog, mode);
        elseif nargin == 23
            du = MPC_QP_core(y, r, A, B, N1, N2, Nu, alpha, lam, reset, ...
                             C, D, wy, umin, umax, dumin, dumax, u_init, du_init, ...
                             L, use_quadprog, mode, u_applied);
        else
            du = MPC_QP_core(y, r, A, B, N1, N2, Nu, alpha, lam, reset, ...
                             C, D, wy, umin, umax, dumin, dumax, u_init, du_init, ...
                             L, use_quadprog, mode, u_applied, solve_when_inactive);
        end
    end
end
